### ISSUE TITLE
Port to SDL2

### ISSUE THREAD

**Issue by fragglet** [fragglet/sdl-sopwith#1]
The codebase still depends on SDL 1.2, which is long obsolete. Transitioning to SDL2 should allow several nice enhancements, such as arbitrary window scaling using hardware acceleration.

**Comment by fragglet** [comment]
Now done, although there are some improvements that can still be made

**Comment by slicer69** [comment]
On this topic, I found the new version of Sopwith (2.0.0) doesn't compile for me anymore on Debian 11, due to a missing linker flag (-lm) in the src/Makefile.

There are a few ways to fix this. I did a quick and dirty edit of src/Makefile.am and changed the line:

     sopwith_LDADD = sdl/libsdlsopwith.a @SDL_LIBS@ sdl/libsdlsopmain.a

to this:

      sopwith_LDADD = sdl/libsdlsopwith.a @SDL_LIBS@ sdl/libsdlsopmain.a -lm

Which added "-lm" to the linker flags and allowed Sopwith to build. There is probably a more elegant way to insert this flag, but this was my quick hack to get 2.0.0 compiling.
